export const API_HOST =
  process.env["NEXT_PUBLIC_API_HOST"] ?? "http://localhost:3000";

export enum Menu {
  DASHBOARD = "sidebar.dashboard",
  STOCK_INHOUSE = "sidebar.stock-inhouse",
  STOCK_ARRIVAL = "sidebar.stock-arrival",
  STOCK_PARTNER = "sidebar.stock-partner",
  DEPOSIT_SALES = "sidebar.deposit-sales",
  DEPOSIT_PURCHASE = "sidebar.deposit-purchase",
  ORDER_REQUEST_SENT = "sidebar.order-request-sent",
  ORDER_REQUEST_RECEIVED = "sidebar.order-request-received",
  TRADE_SALES = "sidebar.trade-sales",
  TRADE_PURCHASE = "sidebar.trade-purchase",
  INHOUSE_PROCESS = "sidebar.inhouse-process",
  PLAN = "sidebar.plan",
  SHIPPING = "sidebar.shipping",
  COLLETED = "sidebar.colleted",
  PAID = "sidebar.paid",
  SECURITIES = "sidebar.securities",
  UNPAID_COLLECTED = "sidebar.unpaid-collected",
  UNPAID_PAID = "sidebar.unpaid-paid",
  TAX_INVOICE = "sidebar.tax-invoice",
  SETTING_ACCOUNT = "sidebar.setting-account",
  SETTING_COMPANY = "sidebar.setting-company",
  SETTING_USER = "sidebar.setting-user",
  SETTING_ROLE = "sidebar.setting-role",
  SETTING_PARTNER = "sidebar.setting-partner",
  SETTING_WAREHOUSE = "sidebar.setting-warehouse",
  SETTING_LOCATION = "sidebar.setting-location",
  SETTING_CARD = "sidebar.setting-card",
  SETTING_ACCOUNTED = "sidebar.setting-accounted",
  SETTING_OFFICIAL_PRICE = "sidebar.setting-official-price",
  SETTING_DISCOUNT_SALES = "sidebar.setting-discount-sales",
  SETTING_DISCOUNT_PURCHASE = "sidebar.setting-discount-purchase",
}
